apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: wbmu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wbmu
    app.kubernetes.io/part-of: byoc-app-vxzq
  name: wbmu
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: wbmu
status:
  loadBalancer: {}
